version: '3.9'

services:
  mongo:
    image: mongo
    container_name: mongodb
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongodata:/data
      - mongodata:/data/db # Essentially, just this volume is enough.
      - mongodata:/data/configdb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_ROOT_USERNAME:-admin}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_ROOT_PASSWORD:-admin123}

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=nvakiet
      - ME_CONFIG_MONGODB_ADMINPASSWORD=nvakiet191
      - ME_CONFIG_MONGODB_SERVER=mongodb

  #TODO: Add web server build

volumes:
  mongodata:
    name: mongodata